config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users, only: %i[index show]

  put '/users/:id', to:  'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'

  resources :articles, only: %i[index new create show destroy] do
    resources :votes, only: %i[create]
  end

  resources :comments, only: %i[new create destroy]
  resources :categories, only: %i[index new create edit update show destrexitoy]

  # Custom route
  get 'category_articles', to: 'articles#category_articles'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  has_many :votes, dependent: :destroy

  validates :content, length: { in: 3..200 }, allow_blank: false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ApplicationHelper

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @article = Article.find(params[:comment][:article_id])
    if @comment.save
      @notification = new_notification(@article.user, @article.id, 'comment')
      @notification.save
      redirect_to @article
    else
      redirect_to @article
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    return unless current_user.id == @comment.user_id

    @comment.destroy
    flash[:success] = 'Comment deleted'
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :article_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-section">
  <% object.comments.each do |c| %>
    <p class="comment_text"><%= c.content %></p>

    <div class="row">
      <div class="col-md-9">
        <p class="the-user">    
          By <%= link_to user_path(c.user), class: "user-name" do %>
            <%= c.user.full_name %>
          <%end%> | 
          Commented <%= distance_of_time_in_words(c.created_at, Time.now) %> ago
        </p>
      </div>
      <div class="col-md-3">
        <p class="delete_comment">
          <% if current_user.id == c.user_id %>
            <%= link_to comment_path(c), method: :delete, data: { confirm: "You sure?" } do %>
              <i class="fa fa-trash hover-red"></i>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for @comment = Comment.new do |f| %>
  <%= render "devise/shared/error_messages", resource: @comment %>
  <%= f.hidden_field :article_id, :value => object.id %>

  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control text-comment" %><br/>

  <%= f.submit("Comment", class: "btn btn-primary btn-comment" ) %>
<% end %>