config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users, only: %i[index show]

  put '/users/:id', to:  'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'

  resources :articles, only: %i[index new create show destroy] do
    resources :votes, only: %i[create]
  end

  resources :comments, only: %i[new create destroy]
  resources :categories, only: %i[index new create edit update show destrexitoy]

  # Custom route
  get 'category_articles', to: 'articles#category_articles'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :votes, dependent: :destroy

  validates :title, length: { in: 3..100 }, allow_blank: false
  validates :content, length: { in: 3..1000 }, allow_blank: false
  validates :image, presence: true
  validates :category_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @categories = Category.all
    @articles = Article.all

    cat = params[:cat]
    @articles = if !cat.nil?
                  Article.where(category_id: cat)
                else
                  Article.all
                end                   
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(articles_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    return unless current_user.id == @article.user_id

    @article.destroy
    flash[:success] = 'Article deleted'
    redirect_back(fallback_location: root_path)
  end

  def category_articles
    @categories = Category.all
    cat = params[:cat]
    @articles = if !cat.nil?
                  Article.where(category_id: cat)
                else
                  Article.all
                end
  end

  private

  def articles_params
    params.require(:article).permit(:title, :content, :image, :category_id)
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_layout.html.erb
<div class="container-fluid article">
  <div class="row">

    <div class="col-md-2">
      <% if object.user.image %>
        <%= image_tag(object.user.image.url, class: "img-profile")%>
      <%end%>
      <p> 
        <%= link_to user_path(object.user), class: "user-full-name" do%>
          <%= object.user.full_name %>
        <%end%>
      </p>
    </div>

    <div class="col-md-10">
      <% unless object.image.empty? %>
        <div class="article-post">
          <p class="image-article-title"><%= image_tag(object.image, class: "article-fill img-bg-fix")%></p>
          <h2 class="article-title"><%= object.title %></h2>
          <p><%= object.content %></p>
          <p><strong>Category: </strong><%= object.category_id %></p>
          <p><small>Posted <%= distance_of_time_in_words(object.created_at, Time.now) %> ago</small></p>
        </div>
      <% else %>
        <div class="article-post">
          <h2 class="article-title"><%= object.title %></h2>
          <p><%= object.content %></p>
          <p><small>Posted <%= distance_of_time_in_words(object.created_at, Time.now) %> ago</small></p>
        </div>
      <% end %>

      <div class="row">
        <div class="user-actions">
          <% if current_user.id == object.user_id %>
            <%= link_to article_path(object), method: :delete, data: { confirm: "You sure?" } do %>
              <i class="fa fa-trash hover-red"> Delete Article</i>
            <% end %>
          <% end %>
        </div>
      </div>

      <hr>
        <div class="row">
          <div class="col-md-12">
            <%= render 'votes/vote_articles', object: object%>
          </div>
        </div>
      <hr>

      <div class="row">
        <div class="col-md-12">
          <h3 class="comments-title">Comments</h3>
          <%= render 'comments/comment', object: object %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= render 'comments/form', object: object %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <%= render "devise/shared/error_messages", resource: @article %>

  <%= f.label :title %>
  <%= f.text_field :title, size: "10x1", class: "form-control" %><br/>

  <%= f.label :content %>
  <%= f.text_area :content, size: "10x10", class: "form-control" %><br/>

  <%= f.label :ImageURL %><br />
  <p>Allow an image in your article by entering a link to the image</p>
  <%= f.text_field :image, placeholder: "http://placekitten.com/1217/400", class:"form-control" %><br/>

  <%= f.label :category_id %><br />
  <%= f.select(:category_id, options_for_select(Category.all.map {|c| [c.category, c.id]}), {}, {class: "form-control"}) %><br/>

  <%= f.submit("Submit Article", class: "btn btn-primary" ) %>
<% end %>

app/views/articles/category_articles.html.erb
<div class="row main-cat-content">
  <% @articles.order(id: :desc).each do |article| %>
    <div class="col-md-6">
      <div class="row between-cat-content">
        <div class="col-md-6 join-jumbotron">
          <div class="jumbotron category-art-image" style="background-image: url(<%= article.image %>)"></div>
        </div>
        <div class="col-md-6">
          <div class="jumbotron category-art-image remove-margin">
            <h3 class="display-6 underline"><%= link_to article.category_id, article_path(article.id) %></h3>
            <h4 class="display-6 title-category"><%= link_to article.title, article_path(article.id) %></h4>
            <p class="lead cat-text"><%= article.content.first(200) %></p>
            <p><%= link_to 'Read more', article_path(article.id) %></p>
          </div>        
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/edit.html.erb
<div class= "row center-content">
  <div class="mx-auto go-half">
    <div class="col-md-12">
      <h1>Editing Article</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-md-9 remove-padding">
    <% @articles.order(id: :desc).limit(1).each do |article| %>
      <div class="jumbotron main-jumbotron img-bg-fix" style="background-image: url(<%= article.image %>)">
        <div class="main-index-text">
          <p class="lead lead-title"><%= link_to article.title, article %></p>
          <p class="body-text"><%= link_to truncate(article.content,:length => 150, :separator => ' '), article %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-3 remove-padding">
    <div class="jumbotron weather-image">
      <p class="lead nairobi">Nairobi, Kenya.</p>
    </div>
  </div>
</div>

<div class="row">
  <% @articles.order(id: :desc).limit(4).each do |article| %>
    <div class="col-md-3 remove-padding">
      <div class="jumbotron category-image" style="background-image: url(<%= article.image %>)">
        <h3 class="category-title"><%= link_to article.category_id, article_path(article.id) %></h3>
        <h4 class="article-category-title"><%= link_to article.title, article_path(article.id) %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class= "row center-content">
  <div class="mx-auto go-half">
    <div class="col-md-12">
      <h1>Create New Article</h1>
      <%= render 'form', article: @article %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<%= render 'articles/article_layout', object: @article %>