config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users, only: %i[index show]

  put '/users/:id', to:  'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'

  resources :articles, only: %i[index new create show destroy] do
    resources :votes, only: %i[create]
  end

  resources :comments, only: %i[new create destroy]
  resources :categories, only: %i[index new create edit update show destrexitoy]

  # Custom route
  get 'category_articles', to: 'articles#category_articles'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category, presence: true
  validates :priority, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:category, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :category %>
  <%= form.text_field :category, class: "form-control" %> <br/>

  <%= form.label :priority %>
  <%= form.select(:priority, options_for_select(['Low', 'Moderate', 'High']), {}, {class: "form-control"}) %> <br/>

  <%= form.submit("Submit Category", class: "btn btn-primary" ) %>        
<% end %>

app/views/categories/edit.html.erb
<div class= "row center-content">
  <div class="mx-auto go-half">
    <div class="col-md-12">
      <h1>Editing Category</h1>
        <%= render 'form', category: @category %> <br>

        <%= link_to 'Show', @category %> |
        <%= link_to 'Back', categories_path %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <% @categories.order(id: :desc).each do |category| %>
    <div class="col-md-3">
      <div class="jumbotron">
        <h4 class="display-6"><%= link_to category.category, category_articles_path(:cat => category.id) %> </h4>
        <p><strong>Priority:</strong> <%= category.priority %></p>
        <%= link_to 'Delete', category, :method => :delete, :confirm => "Are you sure?" %>
      </div>
    </div>
  <% end %>
</div> 

app/views/categories/new.html.erb
<div class= "row center-content">
  <div class="mx-auto go-half">
    <div class="col-md-12">
      <h1>Create New Category</h1>
        <%= render 'form', category: @category %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class= "row center-content">
  <div class="mx-auto go-half">
    <div class="col-md-12">
      <h1>Showing Category</h1>
        <p>
          <strong>Category Name:</strong>
          <%= @category.category %>
        </p>
        <p>
          <strong>Priority:</strong>
          <%= @category.priority %>
        </p>

        <%= link_to 'Edit', edit_category_path(@category) %> |
        <%= link_to 'Back', categories_path %>
    </div>
  </div>
</div>