config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users, only: %i[index show]

  put '/users/:id', to:  'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'

  resources :articles, only: %i[index new create show destroy] do
    resources :votes, only: %i[create]
  end

  resources :comments, only: %i[new create destroy]
  resources :categories, only: %i[index new create edit update show destrexitoy]

  # Custom route
  get 'category_articles', to: 'articles#category_articles'
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-md navbar-fixed-top navbar-dark bg-dark main-nav footer-nav">
    <div class="container-fluid">
        <div class="navbar-collapse collapse nav-content order-2">
            <ul class="nav navbar-nav">
                <%= link_to 'LIFESTYLE', root_path, class: 'nav-link logo footer-link' %>
            </ul>
        </div>
        <ul class="nav navbar-nav text-nowrap flex-row mx-md-auto order-1 order-md-2">
            <li class="nav-item"><a class="nav-link footer-link change-color" href="#">Privacy Policy</a></li>
            <li class="nav-item"><a class="nav-link footer-link change-color" href="#">Terms & Conditions</a></li>
            <li class="nav-item"><a class="nav-link footer-link" href="#">Copyright @2020. All rights reserved.</a></li>
        </ul>
        <div class="ml-auto navbar-collapse collapse nav-content order-3 order-md-3">
            <ul class="ml-auto nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link footer-link" href="#">CONNECT WITH US:</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link footer-link" href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link footer-link" href="#"><i class="fa fa-instagram"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link footer-link" href="#"><i class="fa fa-facebook"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-fixed-top navbar-dark bg-dark main-nav">
    <div class="container-fluid">
        <div class="navbar-collapse collapse nav-content order-2">
            <ul class="nav navbar-nav">
                <%= link_to 'LIFESTYLE', root_path, class: 'nav-link logo' %>
            </ul>
        </div>
        <ul class="nav navbar-nav text-nowrap flex-row mx-md-auto order-1 order-md-2">
          <li class="nav-item">
            <%= link_to 'HOME', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'FASHION', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'BUSINESS', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'SPORTS', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ENTERTAINMENT', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'MAGAZINE', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'TV', root_path, class: 'nav-link' %>
          </li>
        </ul>
        <div class="ml-auto navbar-collapse collapse nav-content order-3 order-md-3">
            <ul class="ml-auto nav navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= button_to saw_notice_path, :class => "text-white btn notice-btn-#{notification_seen}",
                  data: {toggle: 'modal', target: '#noticeModal'}, method: :get, remote: true do %>
                  <% if notification_seen %>
                    <i class="fa fa-bell-slash"></i>
                    <% else %>
                    <i class="fa fa-bell"></i>
                    <% end %>
                  <% end %>
                </li>
                <li class="nav-item dropdown">
                  <a id= "navbarDropdown" class="nav-link dropdown-toggle font-raleway" 
                      href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories <b class="caret"></b>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "Create Category", new_category_path, class: "dropdown-item font-raleway" %>
                    <%= link_to "All Categories", categories_path, class: "dropdown-item font-raleway" %>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a id= "navbarDropdown" class="nav-link dropdown-toggle font-raleway" 
                      href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Articles <b class="caret"></b>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "Create Article", new_article_path, class: "dropdown-item font-raleway" %>
                    <%= link_to "View Articles", articles_path, class: "dropdown-item font-raleway" %>
                  </div>
                </li>                                  
                <li class="nav-item dropdown">
                    <a id= "navbarDropdown" class="nav-link dropdown-toggle font-raleway" 
                        href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      My Account <b class="caret"></b>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <%= link_to "My Profile", user_path(current_user), class: "dropdown-item font-raleway" %>
                      <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item font-raleway", method: :delete %>
                    </div>
                  </li>
                  <% else %>
                    <%= link_to 'LOGIN', new_user_session_path, class: 'nav-link' %>
                    <%= link_to 'REGISTER', new_user_registration_path, class: 'nav-link' %>
                <% end %>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fa fa-search"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<% if user_signed_in? %>
  <%= render 'shared/notifications', object: current_user.notifications%>
<%end%>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LIFESTYLE</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid main">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>

    <% if !current_page?(root_path) %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>